### PR TITLE
Updated to 1.18.1

### PR DESCRIPTION
**Pull request by EvieTheOwl**
No changes to the codebase overall, just did some housework to update too 1.18.1.

Removed the `.idea` folder and updated the `.gitignore` file to the defaults used by the fabric example mod with some exceptions just because from what I can tell it really isn't needed. Let me know if you disagree with this :).

### CODE REVIEW

**Comment by LoganDark** [comment]
> Removed the `.idea` folder and updated the `.gitignore` file to the defaults used by the fabric example mod with some exceptions just because from what I can tell it really isn't needed. Let me know if you disagree with this :).

I do disagree just a bit, since the `.idea` folder contains code formatter settings... and of course the project configuration (!). Additionally, `run_server` is intentionally included because it's annoying to have to write `eula=true` into a file when you first start working on a project.

I can't actually review your PR's code changes because of all the noise caused by the deleted folders. Could you revert those please?

**Comment by EvieTheOwl** [comment]
Thing is the .idea configuration is going to be wrong for most users most of the time. I configured mine to use OpenJDK 17 and others might use the distribution from Oracle for example. It's also extra files that simply aren't needed for what is essentially a dependency for other projects.

**Comment by EvieTheOwl** [comment]
As for the deleted files. Github doesn't fully display them and only displays the files that have been edited so it shouldn't be an issue really

**Comment by LoganDark** [comment]
> Thing is the .idea configuration is going to be wrong for most users most of the time.

I've successfully used it on macOS and Windows. It's expected that you might have to change a couple of settings when loading it up, but it saves a ton of work like using gradle to generate the IDEA configs (because if you don't, you won't have run configurations, etc). Also you seem to have introduced the EULA file into the client folder rather than the server run folder.

> OpenJDK 17

**where?** I can't find OpenJDK 17 anywhere, only "Adoptium", which is the one I had to install.

> As for the deleted files. Github doesn't fully display them and only displays the files that have been edited so it shouldn't be an issue really

https://user-images.githubusercontent.com/4723091/151646201-9791f567-459e-4966-9045-cf2ce340d9a9.mp4

**Comment by EvieTheOwl** [comment]
I haven't introduced it into the wrong folder. With the `.idea` folder removed it defaults to the `/run` folder which is perfectly fine and works just the same

**Comment by EvieTheOwl** [comment]
Oh I see u bundled the java distribution so that's how it worked. Fair enough.
I don't know I just don't think it's needed at all. All you have to do is set the correct java version for the project and gradle and that's it.

**Comment by LoganDark** [comment]
> Oh I see u bundled the java distribution so that's how it worked. Fair enough.

I don't think I did...?

> I don't know I just don't think it's needed at all. All you have to do is set the correct java version for the project and gradle and that's it

The `.idea` folder is for IDE configuration, I'm not vendoring Java. That would be a stupid assumption to make (on my part -- what Java binary contributors would be using) since this is a cross-platform project. I personally started it on a macOS machine and then had to transition to Windows due to my Mac breaking.

**Comment by LoganDark** [comment]
Closing this due to unwanted housekeeping changes. Thanks though :) If you or a friend rely on LanguageHack for a server, you can use this version until I release a 1.18 version myself (if ever). Currently occupied with other things in life...

**Comment by EvieTheOwl** [comment]
Had a look, your right sorry it wasn't bundled. For me it just defaulted java 8.
Java is cross platform anyway so i'm confused why it wouldn't work, i'm running an M1 mac and even the intel x64 version works fine.

The point is it isn't needed, that's all. Other than selecting the correct code formatting that's all it's useful for

**Comment by LoganDark** [comment]
> Java is cross platform anyway so i'm confused why it wouldn't work

The Java virtual machine itself is not cross-platform. In order to vendor Java you'd have to bundle binaries, i.e. the actual `javac` and `java` executables used to compile and run Java programs respectively. You'd need to bundle at least 3:

- One for Windows, which is used by most plebs on this planet
- One for Linux, which can't run Windows executables natively (WINE is a thing but I doubt any IDE supports it)
- One (or two) for macOS, which is currently suffering an ecosystem split that's being papered over by Rosetta 2 (this will go away when the last Intel Mac becomes obsolete and everyone simultaneously deletes all code supporting them)

> The point is it isn't needed, that's all. Other than selecting the correct code formatting that's all it's useful for

It's there for convenience.

**Comment by EvieTheOwl** [comment]
Hmm good point, tbh i'm no genius on the topic but I still don't understand this.

Similarly i've realised after reading through Minecraft's EULA that actually shipping anything with the EULA set to true has to be illegal.

**Comment by LoganDark** [comment]
> Similarly i've realised after reading through Minecraft's EULA that actually shipping anything with the EULA set to true is definitely illegal.

Well, I don't ship the mod with the EULA set to true. I make available my code repository which is my personal workspace where I work on the mod and that just happens to have a text file that contains `eula=true`. With that file in place, if you haven't accepted the EULA already, you are doing so simply by starting the server. The existence of the text file isn't illegal on my part.

**Comment by EvieTheOwl** [comment]
I do get your point it doesn't work like that. You are still hosting the files on Github regardless of if it's packaged.
Anyway i've deleted the fork

**Comment by LoganDark** [comment]
> I do get your point it doesn't work like that. You are still hosting the files on Github regardless of if it's packaged.

What do you mean "it doesn't work like that"? I am hosting the files on GitHub, but like I said in my comment, including the file isn't illegal because it's not bypassing the EULA by any means, anyone who runs the server is still agreeing to it.

**Comment by EvieTheOwl** [comment]
No. A user needs to consciously agree to the EULA regardless. I agree the way they implemented it is pretty bad but pre-setting it to true is completely against the entire purpose of the EULA

**Comment by LoganDark** [comment]
> No. A user needs to consciously agree to the EULA regardless. I agree the way they implemented it is pretty bad but pre-setting it to true is completely against the entire purpose of the EULA

Well fine if you say so. Let me fix it real quick.

**Comment by LoganDark** [comment]
There, it's fixed. I've made sure the README specifies that you're agreeing to the EULA by running the server. Does that count as conscious to you?

**Comment by EvieTheOwl** [comment]
That's not how it works. It's similar to GDPR rules in the UK where there has to be a conscious action. This could be a flip of a switch, press of a "submit" button or in this case setting it from `false` to `true`

**Comment by profjb58** [comment]
Anyway i'm gonna stop replying, this isn't going anywhere fast. I wish u the best either way

**Comment by LoganDark** [comment]
> That's not how it works. It's similar to GDPR rules in the UK where there has to be a conscious action. This could be a flip of a switch, press of a "submit" button or in this case setting it from `false` to `true`

Well that's annoying. Someone could theoretically accidentally clone the repo and accidentally run a Minecraft server and then get upset that they're bound by the EULA of that server that they accidentally ran, and they could've never ever agreed to the Minecraft EULA in the past. Then it would definitely be my fault.

**Pull request closed without merging**
